spring:
  # thymeleaf configuration
  thymeleaf:
    # close cache
    cache: false
  # datasource configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/flashsale?useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/New_York'
    username: 'root'
    password: '000000'
    # default connector
    hikari:
      pool-name: HikariCP
      # minimum number of idle connections
      minimum-idle: 5
      # idle connection timeout: 3min (default timeout: 600000 - 10min)
      idle-timeout: 180000
      # connection timeout: use default 30s
      connection-timeout: 30000
      # maximum lifetime of a connection: use default 30min (0 - forever)
      max-lifetime: 1800000
      # maximum number of connections: use default
      maximum-pool-size: 10
      # auto commit setting: use default - why: https://stackoverflow.com/a/4454419
      auto-commit: true
      # test if connections work (are alive)
      connection-test-query: SELECT 1
  # redis configuration
  redis:
    host: 127.0.0.1
    timeout: 10000ms
    lettuce:
      # max-wait: default -1, unlimited
      max-wait: 10000ms
      # max-idle: default 8
      max-idle: 200
      # min-idle: default 0
      min-idle: 5

mybatis-plus:
  # mapper file
  mapper-locations:
    classpath*:/mapper/*Mapper.xml
  type-aliases-package: yuxm.flashsale

logging:
  # filter logging
  level:
    yuxm.flashsale.mapper: debug




